### ISSUE TITLE
Make http request asynchronous

### ISSUE THREAD

**Issue by sharon-wang** [esse-dev/akita#10]
The HTTP request in #9 is synchronous, but:

```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```

We can fix this using callbacks.

**Comment by vezwork** [comment]
check out [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch), it is the modern way of making Http Requests. Fetch uses [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) to make async HTTP requests.

Simple example usage for getting a json file using HTTP: 
```
async function getJSONFileUsingHTTP() {
  let response = await fetch('akita.com/dogs/file.json');
  let jsonObject = await response.json();
  return jsonObject;
}
```
