### ISSUE TITLE
[BUG] Visits to pages with delayed monetization don't count as monetized visits

### ISSUE THREAD

**Issue by vezwork** [esse-dev/akita#101]
**Describe the bug**
If you visit a page which becomes monetized sometime after the page loads, the page visit will have already been tracked as non-monetized and will not be tracked a monetized visit.

**To Reproduce**
1. Remove Akita and install it in your browser
2. Go to https://www.youtube.com/watch?v=sApKXmwhg4g&amp%3Bab_channel=Simmer.io&ab_channel=Simmer.io
2. Click the Akita browser icon, and hover over the youtube circle under Top Monetized Sites
3. Observe that https://www.youtube.com has 0 monetized views, even though the video linked above is monetized.

**Expected behavior**
Visiting a monetized page should count as a monetized visit, even if the page's payment pointer is added sometime after the page loads. Ideally it would be first counted as a non-monetized visit, but then that non-monetized visit is removed and monetized visit is added when the page becomes monetized.

**Screenshots**
<img src="https://user-images.githubusercontent.com/11082236/103379282-68e61a80-4aa2-11eb-91ca-934766e92810.png" height="400" alt="A screenshot of Akita displaying monetization info for https://www.youtube.com, it says that there are 0 monetized views">

**Desktop (please complete the following information):**
 - OS and Version: macOS 10.15
 - Browser and Version: Chrome 87

**Comment by sharon-wang** [comment]
Just a note: due to the delayed monetization, the favicon also isn't stored.

**Comment by vezwork** [comment]
@sharon-wang does #104 fix the favicon being stored on delayed monetization sites?

**Comment by sharon-wang** [comment]
> does #104 fix the favicon being stored on delayed monetization sites?

Yes that's fixed. To test, visit any delayed monetized site for enough time that it shows in your top sites and the favicon will be in the top site circle. For example, you can visit a monetized YouTube video or a defold game iframe.
