### ISSUE TITLE
Extension does not identify that Twitch.tv is monetized

### ISSUE THREAD

**Issue by vezwork** [esse-dev/akita#12]
Reproducing:
1. Use chrome with Akita and **Coil** installed and activated.
2. Go to https://www.twitch.tv/boxbox or another active streamer's page on Twitch.tv
3. Open developer console and observe that Akita outputs: `siteIsMonetized:  false`
4. Elements view of the developer console shows:
<img width="594" alt="Screen Shot 2020-05-26 at 9 21 09 PM" src="https://user-images.githubusercontent.com/11082236/82974724-e2aba800-9f97-11ea-84b7-22b0d3d03682.png">
5. The Coil extension is streaming money.

Comments:
The monetization meta tag is added dynamically after the page loads. Additionally, if Coil is not installed the meta tag is not added.

**Comment by sharon-wang** [comment]
For reference, Coil Twitch stream info: https://help.coil.com/for-creators/twitch-stream
> For you to receive payments, your viewer must be a Coil Member and must use the Coil Extension. Without the extension running, we won't know to pay you.

**Comment by sharon-wang** [comment]
Since Coil has directly integrated with Twitch, it seems that **only** Coil users are able to tap into web monetization (stream payments) on Twitch. It does not look like Twitch has allowed for general web monetization, such that any web monetization provider can stream payments to Twitch creators.

Because of this, we will not be able to check for monetization on Twitch sites for users of akita who do not have Coil installed/enabled.

**Comment by sharon-wang** [comment]
This may or may not be helpful to us, but I noticed that there is a script in the Twitch site `body` which contains `312: "sites.dev.pages.extension-monetization"`. `312` also appears to have 2 different hashes associated with it. Maybe the hashed values resolve to .js files that do the monetization handling. With that assumption, either those files contain logic to check for the Coil extension, or the Coil extension emits appropriate information to notify the Twitch script that it is enabled. Then, the monetization meta tag is added to `head` with the generated Coil payment pointer.

Could be totally bogus, but just some thoughts. :)

**Comment by vezwork** [comment]
@sharon-wang Thanks for the thoughts, I think this is an interesting direction to look in; BUT I have made significant progress on this issue as a normal part of #8, so it should not be necessary. I plan to submit a PR tomorrow which will solve this issue, as well as being necessary for #8.

**Comment by sharon-wang** [comment]
Great to hear! Looking forward to checking that out 👀
