### ISSUE TITLE
Update installation instructions to include Edge and add install links to README

### ISSUE THREAD

**Issue by sharon-wang** [esse-dev/akita#122]
Akita is now available on Edge! https://microsoftedge.microsoft.com/addons/detail/akita/halamaefcdjalhjgkbefalmhpnboncoc

https://github.com/esse-dev/akita/blob/master/docs/InstallAkita.md needs to be updated to include the link.

We should also have easy-to-access installation links in our README for Chrome, Edge, Firefox (coming soon...).

**Comment by vezwork** [comment]
Here's a resource for edge, firefox, and chrome web store badges: https://github.com/MicrosoftDocs/edge-developer/issues/659
