### ISSUE TITLE
[BUG] Top Site Detail shows "undefined" after visiting a site for a very short period of time

### ISSUE THREAD

**Issue by vezwork** [esse-dev/akita#137]
**Describe the bug**
Top site detail incorrectly shows the text "undefined". 

**To Reproduce**
1. Remove Akita if you already have it installed
2. Install Akita and Coil, pay for Coil (not sure if coil is necessary)
2. In the Akita browser extension pop-up tutorial click on the "puma browser" link
3. Observe that the puma web browser website opens
4. Open the akita browser extension and observe that the puma web browser website does not show in top sites (sleepy akita should be showing).
5. Navigate to a web monetized site like akitaproject.site
6. Open the akita browser extension and observe that the puma web browser website and akitaproject.site show up in top sites.
7. Hover over the puma browser top site circle and see the text "undefined"

**Expected behavior**
In reproduction step 6 the puma web browser website should have shown in top sites. In step 7 the text should say something like "You've spent _ second of monetized time here ..." but it says "undefined"

**Screenshots**
<img src="https://user-images.githubusercontent.com/11082236/114112947-80a41a80-98ab-11eb-8b6a-7d90d0cd149b.png" width="400">

**Desktop (please complete the following information):**
 - OS and Version: macOS 11.2
 - Browser: Chrome

**Comment by vezwork** [comment]
Also saw this after visiting https://defold.itch.io/climberz
<img src="https://user-images.githubusercontent.com/11082236/114113727-5ce1d400-98ad-11eb-9270-84bb62647e92.png" width="400px">

**Comment by sharon-wang** [comment]
I'm also seeing this **without** a Web Monetization provider installed on Brave.

Confirming this happens with the Puma Browser site, but also https://www.grantfortheweb.org/:

![image](https://user-images.githubusercontent.com/25834218/114113758-6b2ff000-98ad-11eb-8515-8af9651d2276.png)

**Comment by sharon-wang** [comment]
I'm thinking this could be related to https://github.com/esse-dev/akita/pull/125, since that touches the extension text. We essentially only made frontend changes this milestone, so not sure what else might have caused this regression.

**Comment by vezwork** [comment]
Also an issue on edge BUT NOT an issue on Firefox.
