### ISSUE TITLE
[BUG] Sites with monetized iframes don't count as monetized on Chrome

### ISSUE THREAD

**Issue by vezwork** [esse-dev/akita#140]
**Describe the bug**
Sites with a monetized iframe (such as https://defold.itch.io/climberz) don't count as monetized on Chrome. This means that the akita icon does not show the monetized state and any time spent on the site does not count as monetized time.

**To Reproduce**
1. Install Akita in Chrome (either with a provider or without, it's broken on both)
2. Go to https://defold.itch.io/climberz
3. Open the game iframe (press "run game")
4. Observe that the akita extension icon does not show the monetized state.
5. Open the akita pop-up and observe that time spent on the site does not count as monetized (the site does not show up in top sites)

**Expected behavior**
The akita extension extension icon monetized state. should show on https://defold.itch.io/climberz after pressing "run game". Time spent on the site should count as monetized.

**Desktop (please complete the following information):**
 - OS and Version: MacOS
 - Browser and Version: Chrome

**Comment by sharon-wang** [comment]
I'm seeing this on Edge without a WM Provider installed.

**Comment by vezwork** [comment]
It seems like this bug was caused by having two simultaneous installations of Akita in Chrome :| oops. In that case, this is a non-issue. 

@sharon-wang I'm not seeing this on Edge without a WM Provider, could you check again?

**Comment by vezwork** [comment]
This issue is caused by having multiple Akita extensions installed (one debug extension and one from extension web store). Akita assigns uuids to iframes and does not have handling for when it encounters a message from an iframe including an unknown uuid (i.e. a uuid assigned to the iframe from the other instance of the akita extension).

**Comment by sharon-wang** [comment]
> @sharon-wang I'm not seeing this on Edge without a WM Provider, could you check again?

Yes, still having this issue. But confirming that this is because I had two versions of Akita installed, failing due to what you've described above.
