### ISSUE TITLE
[BUG] Fetch requests against Gatehub ILP addresses fails on Chromium

### ISSUE THREAD

**Issue by sharon-wang** [esse-dev/akita#144]
**Describe the bug**
Sites with a Gatehub monetization meta tag are not being detected as monetized when visited in a Chromium browser (Chrome, Edge, Brave), but works fine in Firefox.

**To Reproduce**
1. Go to https://www.wevolver.com/ on a Chromium browser
2. Look at Akita extension icon
3. See error

**Expected behavior**
Akita should show that the site is monetized and store monetization data for it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS and Version: Mac
 - Browser and Version: Chrome, Edge, Brave

**Additional context**
This does not occur with Firefox. Having Coil installed (with or without an active subscription) does not seem relevant to this issue.

**Comment by sharon-wang** [comment]
Peeked into some Gatehub docs/posts, but didn't see anything about this:
* https://support.gatehub.net/hc/en-us/articles/360019507633-Interledger-deposit-via-Coil
* https://gatehub.net/blog/make-money-fly-with-coil/

We'll need to investigate why Firefox is doing fine, but Chromium is not working. Something to do with CORS restrictions/strictness.

**Comment by sharon-wang** [comment]
@vezwork Can you test if Gatehub payment pointers pass validation if we force payment pointer validation while Coil is being used?

**Comment by vezwork** [comment]
> @vezwork Can you test if Gatehub payment pointers pass validation if we force payment pointer validation while Coil is being used?

I just

**Comment by sharon-wang** [comment]
Well, it seems like this is no longer an issue as it's not reproducible anymore. Closing.
