### ISSUE TITLE
Test on Firefox, Chrome/Brave, Edge

### ISSUE THREAD

**Issue by sharon-wang** [esse-dev/akita#151]
Test on supported browsers before new submissions to the browser/add-on stores.

Testing guide: https://github.com/esse-dev/akita/issues/128

---

## Non-monetized Testing Guide

```
# Testing as a non-monetized person, without Coil installed unless otherwise stated

- [ ] Brave, with Coil installed but no ongoing subscription
  - [ ] Behaviour after installing for the first time
  - [ ] Behaviour after updating to the latest code
  - [ ] Test clicking links in the popup
  - [ ] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [ ] Change popup threshold to 5000 for 5s and ensure it shows up
  - [ ] verify stats are correct and icon is correct
    - [ ] Test iframes '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)'
    - [ ] Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ)
    - [ ] Test [Twitch.tv](http://twitch.tv) channel
    - [ ] Normal website i.e. [github.com](http://github.com)
    - [ ] Monetized website i.e. [dev.to](http://dev.to)
- [ ] Firefox
  - [ ] Behaviour after installing for the first time
  - [ ] Behaviour after updating to the latest code
  - [ ] Test clicking links in the popup
  - [ ] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [ ] Change popup threshold to 5000 for 5s and ensure it shows up
  - [ ] verify stats are correct and icon is correct
    - [ ] Test iframes '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)'
    - [ ] Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ)
    - [ ] Test [Twitch.tv](http://twitch.tv) channel
    - [ ] Normal website i.e. [github.com](http://github.com)
    - [ ] Monetized website i.e. [dev.to](http://dev.to)
- [ ] Edge
  - [ ] Behaviour after installing for the first time
  - [ ] Behaviour after updating to the latest code
  - [ ] Test clicking links in the popup
  - [ ] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [ ] Change popup threshold to 5000 for 5s and ensure it shows up
  - [ ] verify stats are correct and icon is correct
    - [ ] Test iframes '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)'
    - [ ] Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ)
    - [ ] Test [Twitch.tv](http://twitch.tv) channel
    - [ ] Normal website i.e. [github.com](http://github.com)
    - [ ] Monetized website i.e. [dev.to](http://dev.to)
- [ ] Chrome
  - [ ] Behaviour after installing for the first time
  - [ ] Behaviour after updating to the latest code
  - [ ] Test clicking links in the popup
  - [ ] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [ ] Change popup threshold to 5000 for 5s and ensure it shows up
  - [ ] verify stats are correct and icon is correct
    - [ ] Test iframes '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)' 
    - [ ] Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ)
    - [ ] Test [Twitch.tv](http://twitch.tv) channel
    - [ ] Normal website i.e. [github.com](http://github.com)
    - [ ] Monetized website i.e. [dev.to](http://dev.to)
```

**Comment by vezwork** [comment]
# Testing as a monetized person

- [x] Chrome
  - [x] Behaviour after installing for the first time
  - [x] Behaviour after updating to the latest code
  - [x] Test clicking links in the popup
  - [x] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [x] Change popup threshold to 5000 for 5s and ensure it shows up
  - [x] verify stats are correct and icon is correct
    - [x] Test iframes '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)'
    - [x] Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ)
    - [x] Test [Twitch.tv](http://twitch.tv) channel
    - [x] Normal website i.e. [github.com](http://github.com)
    - [x] Monetized website i.e. [dev.to](http://dev.to)
- [x] Firefox
  - [x] Behaviour after installing for the first time
  - [x] Behaviour after updating to the latest code
  - [x] Test clicking links in the popup
  - [x] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [x] Change popup threshold to 5000 for 5s and ensure it shows up
  - [x] verify stats are correct and icon is correct
    - [x] Test iframes '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)'
    - [x] Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ)
    - [x] Test [Twitch.tv](http://twitch.tv) channel
    - [x] Normal website i.e. [github.com](http://github.com)
    - [x] Monetized website i.e. [dev.to](http://dev.to)
- [x] Edge
  - [x] Behaviour after installing for the first time
  - [x] Behaviour after updating to the latest code
  - [x] Test clicking links in the popup
  - [x] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [x] Change popup threshold to 5000 for 5s and ensure it shows up
  - [ ] verify stats are correct and icon is correct
    - [x] Test iframes '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)' 
    - [x] Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ)
    - [x] Test [Twitch.tv](http://twitch.tv) channel
    - [x] Normal website i.e. [github.com](http://github.com)
    - [x] Monetized website i.e. [dev.to](http://dev.to)

**Comment by sharon-wang** [comment]
# Testing as a non-monetized person, without Coil installed unless otherwise stated

- [x] Brave, with Coil installed but no ongoing subscription
  - [x] Behaviour after installing for the first time
  - [x] Behaviour after updating to the latest code
  - [x] Test clicking links in the popup
  - [x] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [x] Change popup threshold to 5000 for 5s and ensure it shows up
  - [x] verify stats are correct and icon is correct
    - [x] Test iframes '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)'
    - [x] Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ)
    - [x] Test [Twitch.tv](http://twitch.tv) channel
    - [x] Normal website i.e. [github.com](http://github.com)
    - [x] Monetized website i.e. [dev.to](http://dev.to)
- [x] Firefox
  - [x] Behaviour after installing for the first time
  - [x] Behaviour after updating to the latest code
  - [x] Test clicking links in the popup
  - [x] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [x] Change popup threshold to 5000 for 5s and ensure it shows up
  - [x] verify stats are correct and icon is correct
    - [x] Test iframes '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)'
    - [x] Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ)
    - [x] Test [Twitch.tv](http://twitch.tv) channel
    - [x] Normal website i.e. [github.com](http://github.com)
    - [x] Monetized website i.e. [dev.to](http://dev.to)
- [x] Edge
  - [x] Behaviour after installing for the first time
  - [x] Behaviour after updating to the latest code
  - [x] Test clicking links in the popup
  - [x] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [x] Change popup threshold to 5000 for 5s and ensure it shows up
  - [x] verify stats are correct and icon is correct
    - [x] Test iframes '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)'
    - [x] Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ)
    - [x] Test [Twitch.tv](http://twitch.tv) channel
    - [x] Normal website i.e. [github.com](http://github.com)
    - [x] Monetized website i.e. [dev.to](http://dev.to)
- [x] Chrome
  - [x] Behaviour after installing for the first time
  - [x] Behaviour after updating to the latest code
  - [x] Test clicking links in the popup
  - [x] Test that the feedback link points to the correct monetized vs non-monetized survey
  - [x] Change popup threshold to 5000 for 5s and ensure it shows up
  - [x] verify stats are correct and icon is correct
    - [x] Test iframes '[https://defold.itch.io/climberz](https://defold.itch.io/climberz)' 
    - [x] Test Youtube: [https://www.youtube.com/watch?v=9cCqfMJjAWQ](https://www.youtube.com/watch?v=9cCqfMJjAWQ)
    - [x] Test [Twitch.tv](http://twitch.tv) channel
    - [x] Normal website i.e. [github.com](http://github.com)
    - [x] Monetized website i.e. [dev.to](http://dev.to)

**Comment by sharon-wang** [comment]
All our of test cases above passed. Closing!
