### ISSUE TITLE
Keep track of all PRs merged in sketchy hackathon rush

### ISSUE THREAD

**Issue by sharon-wang** [esse-dev/akita#16]
We came to an agreement that we will bypass code review for the last week of the hackathon so that we can more quickly get our changes in.

PRs will be created for any changes we make, but approvals are not required and can changes can be merged right away. PR descriptions will need to include a synopsis of changes made as well as a list of any corners cut in implementation.

The PR name and url needs to be commented in this issue thread, so that we can keep track of all the PRs made in haste. The PR also needs to be assigned the label "sketchy" https://github.com/dog-s/akita/labels/sketchy.

**Comment by sharon-wang** [comment]
Track stream amount and save data to storage: https://github.com/dog-s/akita/pull/14

**Comment by sharon-wang** [comment]
Reorganize project and make indentation consistent: https://github.com/dog-s/akita/pull/19

**Comment by vezwork** [comment]
Set Akita extension icon and extension badge based on the monetization of site: #21

**Comment by sharon-wang** [comment]
Track site visits and time spent on sites: https://github.com/dog-s/akita/pull/23

**Comment by sharon-wang** [comment]
Add Akita icons, expand README and include install steps: https://github.com/dog-s/akita/pull/24

**Comment by vezwork** [comment]
add chart.js library code and use it in popup.js #25

**Comment by vezwork** [comment]
- Might be good to switch over to using Maps https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map instead of objects inside of the data classes. Maps would take a bit more work to serialize and deserialize but would be more natural than the way we are using the objects in the data classes.
- We could abstract / generalize deserialization and move it to a super class of the data objects.

**Comment by vezwork** [comment]
add slideshow and UI without wiring it up #31

**Comment by sharon-wang** [comment]
Add various calculations to use in UI display: https://github.com/dog-s/akita/pull/32

**Comment by sharon-wang** [comment]
change top site detail on hover to an html element and move css to its own file: #43

**Comment by sharon-wang** [comment]
Add favicons to needslove, custom bullets, link colour matches branding #44

**Comment by sharon-wang** [comment]
Retrieve origin favicons and add percent metrics to top site detail #45

**Comment by sharon-wang** [comment]
add new assets for slideshow, add <3 section tooltip #46

**Comment by sharon-wang** [comment]
Improve popup data #47

**Comment by vezwork** [comment]
add custom css tooltip and fix some issues #49

**Comment by sharon-wang** [comment]
Fix various bugs discovered in `#48` testing: #51

**Comment by sharon-wang** [comment]
Allow already resolved payment pointer (https prefix): #52

**Comment by sharon-wang** [comment]
Hide needs love by default until monetized site visited: #53

**Comment by vezwork** [comment]
add sleep akita placeholder illustration #56

**Comment by sharon-wang** [comment]
Fix double link and buggy smooth scroll on firefox: #57

**Comment by sharon-wang** [comment]
Add screenshots/demo and contributing info to README: #59

**Comment by vezwork** [comment]
Rewrite introduction/tutorial carousel from scratch #62

**Comment by sharon-wang** [comment]
Hackathon is over, closing this issue.
