### ISSUE TITLE
UI/UX issues Mac (Firefox and Chrome/Brave)

### ISSUE THREAD

**Issue by sharon-wang** [esse-dev/akita#48]
Related: #41 

The following issues were found during testing in Firefox and Chrome/Brave on Mac.

- [x] **Empty circle space should be filled with something**

![image](https://user-images.githubusercontent.com/25834218/84559441-9c30aa00-ad08-11ea-9699-152019245cd8.png)

- [x] **Should never display 'NaN'**

![image](https://user-images.githubusercontent.com/25834218/84559478-f0d42500-ad08-11ea-8336-5ceb4bd3f801.png)

Moved to #54 
~- [ ] **Circle shouldn't be empty**~
~- [ ] **Favicon loading issue? Image stretched**~

- [x] **Text in circle too small, not easily legible**
![image](https://user-images.githubusercontent.com/25834218/84559636-4957f200-ad0a-11ea-9253-89054f89abe1.png)

- [x] **Mismatched favicon & Empty circle due to no favicon and circle too small for text display**
![image](https://user-images.githubusercontent.com/25834218/84559677-a8b60200-ad0a-11ea-9a21-6d9bf0c19063.png)

Moved to #55.
~- [ ] icon pic in tutorial doesn't match the icon badge in firefox~

- [x] handle single visit/minute/etc, i.e. "1 visits" --> "1 visit"; "1 minutes" --> "1 minute", etc.

**Comment by sharon-wang** [comment]
- [x] Resources cut off in Brave on Mac

![image](https://user-images.githubusercontent.com/25834218/84562693-744f3f80-ad24-11ea-917d-9180742d1023.png)

The spacing issue is resolved once a monetized site is visited
![image](https://user-images.githubusercontent.com/25834218/84562757-f63f6880-ad24-11ea-88dd-57274c178436.png)

"These sites could use some <3" should not be displayed if a user is not using a monetization provider

**Comment by vezwork** [comment]
![image](https://user-images.githubusercontent.com/11082236/84578895-85309d00-ad86-11ea-8b35-1485cc28abab.png)
Websites without favicons are not properly indented in the sites that need love section.

**Comment by sharon-wang** [comment]
> ![image](https://user-images.githubusercontent.com/11082236/84578895-85309d00-ad86-11ea-8b35-1485cc28abab.png)
> Websites without favicons are not properly indented in the sites that need love section.

This problem has been added to issue https://github.com/esse-dev/akita/issues/78.

This issue is complete - closing.
