### ISSUE TITLE
Akita does not pass Firefox extension store JavaScript tests

### ISSUE THREAD

**Issue by vezwork** [esse-dev/akita#65]
Firefox has tests and warnings on upload of an extension to the extension. Akita fails some of these tests and warnings because of
- ~Errors: use of the `?.` operator.~
- ~Errors: use of the `??` operator.~
- [x] Errors: Declaring class properties outside of the constructor.
- [x] Warnings: Use of `.innerHTML` with dynamic content.

**To Reproduce**
1. Package Akita into a .zip
2. Go to https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed
3. Upload akita.zip 
4. View errors and warnings

**Expected behavior**
Firefox extension store should not give any warnings or errors so we can be confident that the extension will be accepted to the extension store.

**Comment by vezwork** [comment]
I'm fixing the `innerHTML` issue while @sharon-wang tackles the declaration of class properties outside of the constructor.

**Comment by sharon-wang** [comment]
[`web-ext`](https://github.com/mozilla/web-ext) seems like a good tool to check if our extension works with Firefox, along with other features like building

Some commands from the `web-ext` readme:
>`run`
Run the extension
`lint`
Validate the extension source
`sign`
Sign the extension so it can be installed in Firefox
`build`
Create an extension package from source
`docs`
Open the web-ext documentation in a browser

`web-ext` Documentation: https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/

**Comment by sharon-wang** [comment]
Ran the Firefox validator on the Akita extension with latest changes, and the validation is passing: `Your add-on was validated with no errors or warnings.`. Closing this issue.
