### ISSUE TITLE
Akita does not pass Chrome Web Store Review

### ISSUE THREAD

**Issue by sharon-wang** [esse-dev/akita#73]
Our initial submission to the Chrome Web Store was rejected. We think that it was rejected due to the browser permissions we've requested - likely the `tabs` or `<all_urls>` permissions. (permissions are specified in the [manifest](https://github.com/dog-s/akita/blob/master/manifest.json))

1) Research
    - Look for guidelines on how to prepare Chrome Web Store submissions/how to properly justify browser permissions, etc.

2) Refactor
    - Check to see if we can remove the `tab` permission or any other permissions
    - Test on Chrome, Firefox after refactoring

3) Resubmit
    - Modify existing submission based on new changes and guidelines from research, and submit

**Comment by sharon-wang** [comment]
Upon looking into `<all_urls>`, it seems to include more than we are actually interested in. We should only enable Akita on http/https websites, captured in the URL patterns `"http://*/*"` and `"https://*/*"`.

`<all_urls>` also includes `ws`, `wss`, `ftp`, `data`, and `file` ([source](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns)), which are not relevant for our extension. As such, we should be able to remove `<all_urls>` without any additional refactoring.

**Comment by vezwork** [comment]
Should we label this release as 1.0.0?

**Comment by sharon-wang** [comment]
> Should we label this release as 1.0.0?

Yes, that makes sense to me too

**Comment by sharon-wang** [comment]
I'm thinking we can change our extension description in the manifest, which is currently
> Get involved in Web Monetization with or without the price tag

to the description we generally use on GitHub and elsewhere to describe Akita
> Insight into your involvement with Web Monetization

Thinking about it a bit more, maybe we should replace "involvement" with "engagement" and use this as our new description everywhere: `Insight into your engagement with Web Monetization`.  "Engagement" feels a bit more fitting and welcoming.

**Comment by vezwork** [comment]
There's two things I can see that we could do in the future to improve our approval chances:

- Move our CORS fetch requests / HttpGet to the background script. (this is necessary when migrating to manifest version v3, but not for v2)
- Use a workaround to avoid code injection of the Akita monetization event listeners. I noticed that Coil dispatches these events on both the `document.monetization` and the `window` objects. Only the `document.monetization` events are guaranteed in web monetization spec, but the `window` object is accessible in content scripts. We could listen for events on the window objects and be able to track monetization events and this would work in practice, but it doesn't align with the spec so there is no guarantee it will continue to work in the future.

**Comment by sharon-wang** [comment]
Let's create a new branch and a release once (fingers crossed!) the extension gets accepted by the Chrome Web Store this time around.

**Comment by sharon-wang** [comment]
Created new branch [chrome-web-store-submission-01012021](https://github.com/esse-dev/akita/tree/chrome-web-store-submission-01012021), which we can use for the release.

**Comment by vezwork** [comment]
Akita passed the Chrome Web Store review and is now published publicly!!! https://chrome.google.com/webstore/detail/akita/phcipgphomfgkenfmjnbmajdiejnlmgg?hl=en&authuser=2

We noticed two issues:

1. The developer email was our non-public email. **This is now fixed and set to our public email dogsdevduo@gmail.com**
2. The screenshots don't look great. They seem to have been scaled down and have become a bit blurry.

**Comment by sharon-wang** [comment]
Our submission to the Chrome Web Store was approved! Created a new release for this beta: https://github.com/esse-dev/akita/releases/tag/v1.0.0-beta.

Chrome Web Store Install Link: https://chrome.google.com/webstore/detail/akita/phcipgphomfgkenfmjnbmajdiejnlmgg
