### ISSUE TITLE
Develop Akita as a cross-browser extension

### ISSUE THREAD

**Issue by sharon-wang** [esse-dev/akita#74]
We have intentions to release Akita on Chrome, Firefox, Edge and possibly other browsers (eg. Opera). Due to browser extension API compatibility differences, we may need to implement slightly different code for different platforms.

For example, we may want to consider a preprocessor solution to include code by platform.

Alternatively, we can opt to target Firefox as our dominant browser and use a polyfill API to provide coverage to other browsers. The webextension-polyfill is Mozilla's suggested API to use: https://github.com/mozilla/webextension-polyfill/.

More info here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension

Browser Availability:
- [x] Chrome Web Store
    - https://chrome.google.com/webstore/detail/akita/phcipgphomfgkenfmjnbmajdiejnlmgg
- [x] Firefox Add-ons:
    - https://addons.mozilla.org/en-CA/firefox/addon/akita/
- [x] Microsoft Edge Add-ons
    - https://microsoftedge.microsoft.com/addons/detail/akita/halamaefcdjalhjgkbefalmhpnboncoc

**Comment by vezwork** [comment]
Apple's new guide to converting an existing extension to a safari extension: https://developer.apple.com/news/?id=qiz0arxc

**Comment by sharon-wang** [comment]
Just a note that we've submitted our extension to the Microsoft Edge store. We followed pretty much the same process as submitting to Chrome Web Store, but it was a bit less work (there was no section to justify our manifest permissions, which Chrome required). There was a section to provide extra information for testers (logins/accounts for testing; other supplementary info) in the Edge store submission which Chrome does not have.

Update: We're on Edge now! https://microsoftedge.microsoft.com/addons/detail/akita/halamaefcdjalhjgkbefalmhpnboncoc

**Comment by sharon-wang** [comment]
Created https://github.com/esse-dev/akita/issues/155 in case we consider developing Akita for Safari in the future.

**Comment by sharon-wang** [comment]
We've submitted our latest release to Chrome and Edge, and have submitted to Mozilla for the first time 🎉 Approvals pending...

**Comment by sharon-wang** [comment]
For the latest release, Akita 1.1.1: 

- Chrome: approved! ✅ 
- Edge: approved! ✅ 
- Firefox: approved! ✅

**Comment by sharon-wang** [comment]
We're now live on Chrome, Firefox and Edge! 🎉🎉 Closing this.
