### ISSUE TITLE
Web Monetized Site Discoverability

### ISSUE THREAD

**Issue by vezwork** [esse-dev/akita#80]
Provide functionality in the Akita extension to recommend new web monetized sites based on the sites you have visited.

**Comment by sharon-wang** [comment]
Coil Developers list of Web Monetized sites/creators: https://developers.coil.com/community/who-is-web-monetized

Coil Discover list of Web Monetized content/sites/etc: https://coil.com/explore

**Comment by sharon-wang** [comment]
This is no longer part of our development plans. Closing!
